#ifndef LSYSTEMS_GLOBAL_H
#define LSYSTEMS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LSYSTEMS_LIBRARY)
#  define LSYSTEMSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LSYSTEMSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LSYSTEMS_GLOBAL_H
